apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deployment
  labels:
    app: movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies-container
          image: nitishkumar06/go-movies:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always