apiVersion: v1
kind: Service
metadata:
  name: movies-service
  labels:
    app: movies
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: movies